---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

#Entendendo as variáveis

#observar frequencias absolutas e relativas
```{r}

#Estado Civil
freq_absoluta = table(func_t$civil)
freq_relativa = prop.table(freq_absoluta)*100

t(rbind(freq_absoluta, freq_relativa))

```


```{r}
#regiao

freq_absoluta = table(func_t$regiao)
freq_relativa = prop.table(freq_absoluta)*100

t(rbind(freq_absoluta, freq_relativa))

freq_absoluta = table(func_t$civil)
freq_relativa = prop.table(freq_absoluta)*100

t(rbind(freq_absoluta, freq_relativa))
  
```

#Visualizacao gráfica
Gráfico de barras
```{r}
bp = barplot(table(func_t$civil), col = c("blue", "red"))
text(bp, 0, c(16, 20), cex=1, pos=3)
```

#Gráfico de pizza
```{r}
#grafico de pizza
fatias <- c(16, 20)
rotulos <- c("solteiro", "casado")
percent <- round (fatias/sum(fatias)*100, digits = 1)
rotulos <- paste (rotulos, percent) # acrescenta as percentagens
rotulos <- paste (rotulos, "%", sep="")

pie(fatias, labels = rotulos, col=c("indianred2", "lightseagreen"))
```

#Juntando os gráficos
```{r}
par (mfrow = c(1, 2))

bp = barplot(table(func_t$civil), col = c("indianred2", "lightseagreen"))

#grafico de pizza
fatias <- c(16, 20)
rotulos <- c("solteiro", "casado")
percent <- round (fatias/sum(fatias)*100, digits = 1)
rotulos <- paste (rotulos, percent) # acrescenta as percentagens
rotulos <- paste (rotulos, "%", sep="")

pie(fatias, labels = rotulos, col=c("indianred2", "lightseagreen"))


# Criando gráfico de pizza com o ggplot
ggplot(func_t, aes(x=factor(1), fill=civil))+
  geom_bar(width = 1)+
  coord_polar("y")

```


```{r}
library(tidyverse)
library(magrittr)
library(dplyr)
library(ggplot2)
```
#Visualização Gráfica Boxplot


#Será que o salário diferem por diferentes graus de instrução?
```{r}
boxplot(salario ~ instrucao, data=func_t)

#salário difere por regiao?
boxplot(salario ~ regiao, func_t)
```

#Existe diferença enrtre salário x grau de instrução x região ?

```{r}
ggplot(data=func_t) +
  geom_boxplot(mapping = aes (x = regiao, 
                              y = salario,
                              color = instrucao))+
  facet_grid((regiao ~ .))
```


